### ISSUE TITLE
Bug - Usage calculation

### ISSUE THREAD

**Issue by shupershuff** [Rustrician/rustrician-public#14]
I've noticed that in some circuits the usage calculation on a large battery will be under 100 despite the battery being 100% utilised.
It appears as if branches themselves are _sometimes_ not having their unit costs calculated, but not totally sure.

Quick example circuit can be seen here: https://www.rustrician.io/?circuit=a8fe8273231a559a60aec4019d09a632

**Comment by Swiftcoyote** [comment]
Electrical Branches do not have any active usage for themselves, only what the branch out it set to.
